:title: Voxel Carving of 3D Surfaces using AR Markers for Pose Estimation
:description: Voxel Carving Project for 3D Scanning Course
:keywords: cpp, tum, voxel, voxel carving
:authors: Maximilian Anzinger <maximilian.anzinger@tum.de>; Alexander Fuchs <fuchsale@in.tum.de>; Georg Henning <georgm.henning@tum.de>; Nils Keunecke <nils.keunecke@tum.de>;
:revremark:
:showtitle:
:sectnums:
:toc: preamble
:toclevels: 3
:icons: font

:cmake_version: 3.9.1
:git-bash_version: 2.14.1
:opencv_version: 0.0

= {title}

Final project for "3D Scanning and Motion Capture" class in SS2022 at Technical University of Munich.

== Abstract
`TODO`

== Setup

Install https://eigen.tuxfamily.org/index.php?title=Main_Page [Eigen] (Version 3.4).

Install https://docs.opencv.org/3.4/d3/d52/tutorial_windows_install.html[OpenCV Library] (Visual Studio 2019 VC16).

=== Clone the repository

.Repository Structure

* Data
** demo_material
*** images
*** masks
* Libs
* src
* CMakeLists.txt
* README.adoc

.Data
You can use `Data` to store images, masks, and calibration files of models you want to carve. The subfolder `demo_material` contains all inputs and outputs used to generate the model as described in section <<howto, 4>>.

.Libs
If you have never worked with `OpenCV` or `Eigen` you can follow the instructions below and install these libraries in the `Libs` directory.

.src
This directory contains the implementation of this project.

=== Windows

==== CMake
image:https://img.shields.io/badge/CMake-{cmake_version}+-brightgreen[CMake Version]

. Download https://cmake.org/download/[`CMake`] ({cmake_version} or newer)
. Install `CMake` in your prefered directory.
. Add `CMake` to `PATH` variable.

==== Git BASH
image:https://img.shields.io/badge/Git BASH-{git-bash_version}+-brightgreen[Git BASH Version]

. Download and install https://gitforwindows.org/[`Git Bash`] ({git-bash_version} or newer)

==== Eigen
Download and extract `Eigen` (see https://eigen.tuxfamily.org/dox/GettingStarted.html[Eigen - Getting started]).

==== OpenCV
image:https://img.shields.io/badge/Open CV-{opencv_version}+-brightgreen[OpenCV Version]

. Navigate to the directory where you wish to install `OpenCV` (eg. `{directory}/AR_Voxel_Project/Libs`)
. create new file `installOCV.sh` with the following content:
+
[source, shell]
----
#!/bin/bash -e

# taken from: https://docs.opencv.org/3.4/d3/d52/tutorial_windows_install.html

myRepo=$(pwd)
CMAKE_GENERATOR_OPTIONS=-G"Visual Studio 17 2022"
#CMAKE_GENERATOR_OPTIONS=-G"Visual Studio 16 2019"
#CMAKE_GENERATOR_OPTIONS=-G"Visual Studio 15 2017 Win64"
#CMAKE_GENERATOR_OPTIONS=(-G"Visual Studio 16 2019" -A x64)  # CMake 3.14+ is required
if [  ! -d "$myRepo/opencv"  ]; then
    echo "cloning opencv"
    git clone https://github.com/opencv/opencv.git
else
    cd opencv
    git pull --rebase
    cd ..
fi
if [  ! -d "$myRepo/opencv_contrib"  ]; then
    echo "cloning opencv_contrib"
    git clone https://github.com/opencv/opencv_contrib.git
else
    cd opencv_contrib
    git pull --rebase
    cd ..
fi
RepoSource=opencv
mkdir -p build_opencv
pushd build_opencv
CMAKE_OPTIONS=(-DBUILD_PERF_TESTS:BOOL=OFF -DBUILD_TESTS:BOOL=OFF -DBUILD_DOCS:BOOL=OFF  -DWITH_CUDA:BOOL=OFF -DBUILD_EXAMPLES:BOOL=OFF -DINSTALL_CREATE_DISTRIB=ON)
set -x
cmake "${CMAKE_GENERATOR_OPTIONS[@]}" "${CMAKE_OPTIONS[@]}" -DOPENCV_EXTRA_MODULES_PATH="$myRepo"/opencv_contrib/modules -DCMAKE_INSTALL_PREFIX="$myRepo/install/$RepoSource" "$myRepo/$RepoSource"
echo "************************* $Source_DIR -->debug"
cmake --build .  --config debug
echo "************************* $Source_DIR -->release"
cmake --build .  --config release
cmake --build .  --target install --config release
cmake --build .  --target install --config debug
popd
----
. Adjust the `CMAKE_GENERATOR_OPTIONS` according to your Visual Studio version.
. In git command line enter the following command:
+
[soruce, shell]
----
./installOCV.sh
----
+
This script will generate the required installation of `Open CV` in the current directory (eg. `{directory}/AR_Voxel_Project/Libs/install/opencv`).
. Keep in mind that this will take some time.
. Add `{directory}\Libs\install\opencv\bin` to PATH.
. For further information please check the https://docs.opencv.org/3.4/d3/d52/tutorial_windows_install.html[official OpenCV website].

=== Other OS
Please refere to the following instructions:

* Eigen: https://eigen.tuxfamily.org/dox/GettingStarted.html[All OS]
* Open CV: https://docs.opencv.org/3.4/d7/d9f/tutorial_linux_install.html[Linux] https://docs.opencv.org/3.4/d0/db2/tutorial_macos_install.html[MacOS]

=== Build the Project

After installing both libraries, your repository should look like this.

.Repository Structure

* Data
** demo_material
*** images
*** masks
* Libs
** Eigen3
** opencv
** install
*** opencv
** opencv_contrib
* src
* CMakeLists.txt
* README.adoc

Now you are ready to generate the project using `CMake`. If you followed the instructions above, `CMake` should already have found the installation directories of `Eigen` and `OpenCV`. Make shure that `Eigen3_DIR` and `OpenCV_DIR` are set correctly.

After compiling the project, you are ready to carve your first model.




== Example
`TODO`

== How to run?

[#howto]
`TODO`

=== Generate ChArUco Board

.Run

[source,shell]
----
$ ./voxel_project.exe -c=1
----

This command will generate a new subdirectory `out` containing the file `BoardImage.jpg`. This ChArUco Board can be used to calibrate your individual camera and later on carve your own models.

=== Camera Calibration

.Run

[source,shell]
----
$ ./voxel_project.exe -c=2
----

`TODO`

=== Segmentation

.Run

[source,shell]
----
$ ./voxel_project.exe -c=3
----

`TODO`

=== Carve your own model

.Run

[source,shell]
----
$ ./voxel_project.exe -c=5 -images="<images-dir>" -masks="<masks-dir>" -calibration="<cameracalibartion.yml-dir>" -carve=<carving-method> -x=<x-dim> -y=<y-dim> -z=<z-dim> -size=<voxel-size> -scale=<model-scale> -dx=<x-offset> -dy=<y-offset> -dz=<z-offset> -color=<color-method> -postprocessing=<postprocessing-method>
----

This command will generate a new file `out/mesh.off` containing the mesh generated by carving your specified inputs. To understand more about the flags please refere to the table below.

.Flags

|====
| Flag | Default | Description

| -images="<images-dir>"
| NonOptional
| Directory of the input images e.g. `./Data/demo_material/images`.

| -masks="<masks-dir>" 
| NonOptional
| Directory of the masks e.g. `./Data/demo_material/masks`.

| -calibration="<cameracalibartion.yml-dir>"
| NonOptional
| Directory of the masks e.g. `./Data/demo_material/cameracalibration.yml`.

| -carve=<carving-method>
| 1
a|
* `1` - standard carving
* `2` - greedy carving (fast)

| -x=<x-dim>
| 100
| Number of voxels in x direction.

| -y=<y-dim>
| 100
| Number of voxels in y direction.

| -z=<z-dim>
| 100
| Number of voxels in z direction.

| -size=<voxel-size>
| 0.0028
| Side length of a voxel.

| -scale=<model-scale>
| 1.0
| Scale factor for the output model.

| -dx=<x-offset>
| 0.0
| Move output model in x direction (unscaled).

| -dx=<y-offset>
| 0.0
| Move output model in y direction (unscaled).

| -dx=<z-offset>
| 0.0
| Move output model in z direction (unscaled).

| -color=<color-method> 
| 0
a|
* `0` - no color reconstruction
* `1` - nearest observer
* `2` - average color

| -postprocessing=<postprocessing-method>
| true
a|
* `true` - apply postprocessing on the model
* `false` - do not apply postprocessing

|====

`TODO`

=== Benchmarking

.Run

[source,shell]
----
$ ./voxel_project.exe -c=6 -images="<images-dir>" -masks="<masks-dir>" -calibration="<cameracalibartion.yml-dir>"
----

This command will execute the provided benchmarking cases on the specified data. For each case a mesh file will be generated in `out/bench`. Additionally, the bash will print a table containing information about the test cases and exectuion times (see table below).
For more information about the flags please refer to the table above. 

.Benchmark output

|====
| Column | Description |

| Name
| Short description of the testcase
a|
* Model size (Small, Medium, Large)
* Carving method (`1` - standard, `2`- greedy)
* Coloring mehtod

| Model size
| Model dimensions (x, y, z direction) and voxel size

| Carving time
| Time needed to execute carving process (in milliseconds)

| Coloring time
| Time needed to execute coloring process (in milliseconds)

| Postprocessing time
| Time needed for postprocessing (in milliseconds)

| Marching cubes time
| Time needed to transform model into `.off`-format sutiable representation using the marching cubes algorithm (in milliseconds)

| Overall time
| Time needed for complete reconstruction process (including output file writing and variable initializations, excluding image loading) (in milliseconds)

|====

`TODO`

== References
`TODO`